added cup of join
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-noa-seneor pull request #3
Opened 2022-03-20 00:41 UTC by noa-seneor

cup of join

2022-03-20 12:35 UTC, itayday commented on cup_of_join.py
> +def join(*parameters, sep='-'):
Please add documantation to your function.

2022-03-20 12:35 UTC, itayday commented on cup_of_join.py
> +    for i in range(len(parameters)-1):
Is there a way to simplify your code here? (what about using list comprehension?)

2022-03-30 07:58 UTC, lovodkin93 requested changes

2022-03-30 07:58 UTC, lovodkin93 commented on cup_of_join.py
> +    """
please explain the purpose of the paramters in the documentation.

2022-03-30 08:05 UTC, lovodkin93 approved these changes

2022-03-30 08:05 UTC, lovodkin93 commented on cup_of_join.py
> +    """
much better!

2022-03-30 08:13 UTC, merged