added piece of cake
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-noa-seneor pull request #4
Opened 2022-03-20 00:41 UTC by noa-seneor

חתכת עוגה

2022-03-20 12:37 UTC, itayday commented on piece_of_cake.py
> +def get_recipe_price(prices, optionals=[], **ingredients):
Please add documantation to your function, and try to simplify your code as mentioned in the other notes i gave you :)

2022-03-30 07:48 UTC, lovodkin93 requested changes

2022-03-30 07:48 UTC, lovodkin93 commented on piece_of_cake.py
> +    receives as parameter a dictionary of ingredients : price for 100gr ,
the documentation isn't written according to the standard where each parameter is described in a separate line

2022-03-30 08:03 UTC, lovodkin93 approved these changes
good job!

2022-03-30 08:13 UTC, merged